# Generated by Django 4.1.7 on 2024-03-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Convenor',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='FacultyRoleAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_role', models.CharField(blank=True, max_length=150, verbose_name='area expertise')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRoleModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_role', models.CharField(blank=True, max_length=150, verbose_name='area expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('interested_category', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_submission_date', models.DateField()),
                ('project_target_completion_date', models.DateField()),
                ('project_submission_status', models.BooleanField(default=False)),
                ('project_issue_date', models.DateTimeField(auto_now_add=True)),
                ('list_of_academics', models.ManyToManyField(to='users.facultyroleacademic')),
                ('moderator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.facultyrolemoderator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verify_status', models.BooleanField(default=False)),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facultyroleacademic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='FinalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalmark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facultyrolemoderator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='facultyrolemoderator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.AddField(
            model_name='facultyrolemoderator',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AddField(
            model_name='facultyroleacademic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.AddField(
            model_name='facultyroleacademic',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
    ]
