# Generated by Django 4.1.7 on 2024-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyroleacademic',
            name='faculty_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AlterField(
            model_name='facultyrolemoderator',
            name='moderator_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
