# Generated by Django 4.1.7 on 2024-03-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_facultyroleacademic_faculty_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmark',
            name='moderator',
        ),
        migrations.AlterField(
            model_name='finalmark',
            name='finalmark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='list_of_academics',
            field=models.ManyToManyField(blank=True, null=True, to='users.facultyroleacademic'),
        ),
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='moderator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.facultyrolemoderator'),
        ),
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='project_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='project_target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
