# Generated by Django 4.1.7 on 2024-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_finalmark_moderator_alter_finalmark_finalmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='list_of_academics',
            field=models.ManyToManyField(blank=True, to='users.facultyroleacademic'),
        ),
    ]
