# Generated by Django 4.1.7 on 2024-03-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_projectassignmentstatus_list_of_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='project_issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
