# Generated by Django 4.1.7 on 2024-03-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_projectassignmentstatus_project_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.facultyrolemoderator'),
        ),
    ]
