# Generated by Django 4.1.7 on 2024-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_projectassignmentstatus_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignmentstatus',
            name='project_issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
