# Generated by Django 4.1.7 on 2024-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_projectassignmentstatus_project_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmark',
            name='finalmark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
